### ISSUE TITLE
Consider moving to ember-auto-import

### ISSUE THREAD

**Issue by Techn1x** [rtablada/ember-css-properties#1]
I was just going through my packages and noticed a package called `ember-cli-cjs-transform`, wasn't sure what it was, but after some detective work I figured out that this addon is what added it to my packages.json via the blueprint

I am guessing you use `ember-cli-cjs-transform` in order to import and use `cssesc`, maybe consider moving to using `ember-auto-import` as it seems to be the best addon for importing JS nowadays (The readme should detail how to use it in addons).

https://github.com/ef4/ember-auto-import

Thanks for the super useful addon by the way! My addon retrieves colour hex's from a server, and then uses that for an element's background-color, so binding to style attributes is essential.

**Comment by buschtoens** [comment]
Published as `ember-css-properties@0.2.0`. 🎉
